### ISSUE TITLE
DeepSeek V3でデータセットができたのですがどこに置けばよいでしょうか

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/e2k#24]
## 内容

タイトルのとおりです。
とりあえずissue作ってみました！

### 実現方法

ちょっとコードをいじって実行しました 🙇 
trimして、バッチサイズを`90`で固定しています。（並列数を上げられるのでこっちのほうが速い）

<details><summary>diff</summary>

```diff
diff --git a/dataset/src/inference/openai.ts b/dataset/src/inference/openai.ts
index 04f7ea9..cb0aee2 100644
--- a/dataset/src/inference/openai.ts
+++ b/dataset/src/inference/openai.ts
@@ -50,8 +50,8 @@ export class OpenAI extends InferenceProvider {
     const resultPattern = /^([a-z]+)=(.+)$/gm;
     const results = Object.fromEntries(
       [...response.matchAll(resultPattern)].map((match) => [
-        match[1],
-        match[2],
+        match[1].trim(),
+        match[2].trim(),
       ]),
     );
 
diff --git a/dataset/src/main.ts b/dataset/src/main.ts
index 1fd71c6..61052a5 100644
--- a/dataset/src/main.ts
+++ b/dataset/src/main.ts
@@ -51,7 +51,8 @@ async function main() {
 
   console.log("2: Finding maximum batch size...");
   // ちょっと余裕を持たせる
-  const maxBatchSize = await findMaxBatchSize(inferenceProvider, words, random);
+  // const maxBatchSize = await findMaxBatchSize(inferenceProvider, words, random);
+  const maxBatchSize = 100;
   const batchSize = Math.floor(maxBatchSize * 0.9);
   console.log(`Batch size: ${batchSize}`);
 
@@ -155,7 +156,9 @@ async function inferPronunciations(
       const results = await inferenceProvider.infer(words);
 
       console.log(
-        `Inferred ${Object.keys(results).length} pronunciations, ${shuffledWords.length - Object.keys(allResults).length} remaining`,
+        `Inferred ${Object.keys(results).length} pronunciations, ${
+          shuffledWords.length - Object.keys(allResults).length
+        } remaining`,
       );
 
       Object.assign(allResults, results);
@@ -185,11 +188,11 @@ async function inferPronunciations(
         result.status === "rejected" ? [result.reason] : [],
       );
       const error = new AggregateError(errors);
-      if (errors.some((err) => !String(err).includes("429"))) {
-        throw error;
-      }
+      // if (errors.some((err) => !String(err).includes("429"))) {
+      //   throw error;
+      // }
 
-      console.error(`Rate limited, waiting ${rateLimit.waitMs}ms...`);
+      // console.error(`Rate limited, waiting ${rateLimit.waitMs}ms...`);
       console.error(error);
       await new Promise((resolve) => setTimeout(resolve, rateLimit.waitMs));
     }
```

</details>

<details><summary>サンプル</summary>

```jsonl
{"word":"pavelko","kata":["パヴェルコ"]}
{"word":"headcount","kata":["ヘッドカウント"]}
{"word":"fukuoka","kata":["フクオカ"]}
{"word":"mcfeely","kata":["マクフィーリー"]}
{"word":"marliave","kata":["マリアーヴ"]}
{"word":"ingested","kata":["インジェステッド"]}
{"word":"kaolin","kata":["カオリン"]}
{"word":"dinky","kata":["ディンキー"]}
{"word":"alonge","kata":["アロンジェ"]}
{"word":"bakersfield","kata":["ベイカースフィールド"]}
{"word":"witless","kata":["ウィットレス"]}
{"word":"vented","kata":["ベンテッド"]}
{"word":"contura","kata":["コントゥラ"]}
{"word":"stello","kata":["ステロ"]}
{"word":"kerchner","kata":["カーチナー"]}
{"word":"boileau","kata":["ボワロー"]}
{"word":"zummo","kata":["ズンモ"]}
{"word":"bon","kata":["ボン"]}
{"word":"sentelle","kata":["センテル"]}
{"word":"provenzano","kata":["プロヴェンツァーノ"]}
{"word":"hudnall","kata":["ハドナール"]}
{"word":"unbowed","kata":["アンボウド"]}
{"word":"vortex","kata":["ヴォルテックス"]}
{"word":"jergens","kata":["ジャーゲンス"]}
{"word":"stern","kata":["スターン"]}
{"word":"stober","kata":["ストーバー"]}
{"word":"biddable","kata":["ビダブル"]}
```

</details>

<details><summary>設定</summary>

```
# yaml-language-server: $schema=./config.schema.yml

# 乱数のシード。
randomSeed: 0

source:
  # 英単語の取得方法を指定します。
  provider: cmudict

  # 最大の単語数。"all"で全ての単語を取得します。
  maxNumWords: "all"
  # maxNumWords: 300

inference:
  # 読みの取得方法を指定します。
  # "gemini"、"openai" が選択可能です。
  provider: openai

  # 並列実行数。レートリミットとの兼ね合いで調整してください。
  concurrency: 300

  rateLimit:
    # レートリミットに引っかかった場合のリトライ回数。
    maxRetries: 100

    # リトライ時の待ち時間。
    waitMs: 60000

    # 1回のリクエスト間の待ち時間。
    throttleMs: 50

  # Geminiの設定。
  gemini:
    # Google AI Studioから取得したAPIキー。
    apiKey: ""

    # 使うモデルの名前。
    modelName: "gemini-2.0-flash"

  # OpenAI互換APIの設定。
  openai:
    # APIのベースURL。
    apiBaseUrl: "https://openrouter.ai/api/v1"

    # APIキー。
    apiKey: "**********"

    # 使うモデルの名前。
    # modelName: "deepseek/deepseek-chat:free" # 無料、1日200回まで、V3と同じ
    # modelName: "deepseek/deepseek-r1" # 有料、reasoning？
    modelName: "deepseek/deepseek-chat" # 有料、V3
```

</details>

commitish: e6e699e51b474171a89f63ad86f8c276797e5cd6

できたファイル: [data.jsonl.zip](https://github.com/user-attachments/files/19290609/data.jsonl.zip)

Invalid pronunciation:
<details>

```
Invalid pronunciation for showed: ショーed
Invalid pronunciation for suv: SUV
Invalid pronunciation for caressed: カressed
Invalid pronunciation for lawnmower: ローン・モアー
Invalid pronunciation for granddaughter: グランド・ドーター
Invalid pronunciation for awning: オー二ング
Invalid pronunciation for suvs: SUVズ
Invalid pronunciation for valuevision: バリュー・ビジョン
Invalid pronunciation for schoepe: ショーペ  relaxation=リラクセーション  attrition=アトリション  fuklah=フクラー  equations=イクエイションズ  garratt=ギャラット  gjelten=ゲルテン  sculpt=スカルプト  collet=コレット  camco=カムコ  nonqualified=ノンクオリファイド  softdrink=ソフトドリンク  ostensibly=オステンブリー  decontrolled=ディコントロールド  leder=レダー  headrick=ヘドリック  improvements=インプルーブメンツ  guyette=ガイエット  motivational=モティベーショナル  venuti=ヴェヌティ  curves=カーブズ  proprietary=プロプライエタリー  reachable=リーチャブル  opprobrium=オプロブリウム  hickam=ヒッカム  luckett=ラケット  yamashita=ヤマシタ  henriette=ヘンリエット  cortright=コートライト  hargett=ハーゲット  ganley=ガンリー  distressingly=ディストレッシングリー  salvaging=サルベイジング  malle=マレ  megabucks=メガバックス  vaccinated=ヴァクシネイテッド  greth=グレス  wound=ウーンド  erina=エリナ  rockville=ロックヴィル  cherubini=ケルビーニ  wernicke=ヴェルニッケ  covell=コベル  realists=リアリスト  burros=ブロス  marcou=マルコウ  matt=マット  raether=レーター  mandler=マンドラー  petulant=ペチュラント  beyonce=ビヨンセ  stavola=スタヴォラ  racier=レイシアー  viano=ヴィアノ  cree=クリー  shadduck=シャダック  aylwin=エイルウィン  sorensen=ソレンセン  itinerary=アイティネラリー  whiting=ホワイティング  egerer=エガラー  megill=メギル  serpents=サーペンツ  thorstad=トールスタッド  account=アカウント  microwaved=マイクロウェイブド  schellhase=シェルハーゼ  redevelopment=リディベロップメント  charlottetown=シャーロットタウン  dispersing=ディスパーシング  altron=アルトロン  kusserow=クッセロウ  inconsistency=インコンスィステンシー  ranches=ランチズ  dougal=ドゥーガル
Invalid pronunciation for disciplinarians: ディシプリンarians
Invalid pronunciation for branscomb: ブランmmasrikom
Invalid pronunciation for freezing: freezer#フリージング
Invalid pronunciation for benker: ベンカ−
Invalid pronunciation for schauble: シャウブレe
Invalid pronunciation for hula: フラ RNA
Invalid pronunciation for tvedt: ドヴェット
Invalid pronunciation for turkel: ターテel
Invalid pronunciation for spiegelberg: シュピーゲルバesch
Invalid pronunciation for berget: バーグエt
Invalid pronunciation for dietrich: ディートリch
Invalid pronunciation for holdouts: ホールドアウt
Invalid pronunciation for clickbait: クリックベイt
Invalid pronunciation for secateur: セカトeur
Invalid pronunciation for crnkovich: クルンコビch
Invalid pronunciation for councilwomen: カウンシルウomen
Invalid pronunciation for inefficiencies: イネフィシens
Invalid pronunciation for bruzzese: ブルッzese
Invalid pronunciation for shortage: ショートage
Invalid pronunciation for sanrio: サンrio
Invalid pronunciation for guzy: グージーdohnanyi=ドハニー
Invalid pronunciation for unpainted: アンペインド
Invalid pronunciation for unwrapped: アンラップド
Invalid pronunciation for unkempt: アンケンプド
```

</details>
