### ISSUE TITLE
crates.ioに公開する？

### ISSUE THREAD

**Issue by sevenc-nanashi** [VOICEVOX/e2k#45]
## 内容

Rust側をcrates.ioに上げたいです。

### Pros 良くなる点

Rustユーザーが喜ぶ

### Cons 悪くなる点

ないはず？

### 実現方法

（なし）

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [ ] macOS
- [ ] Linux

## その他

（なし）

**Comment by Hiroshiba** [comment]
crates.io はよく知らないのですが、organization機能はありそうでしょうか？ 👀 
あるいはチームアカウントのようなものがあって、いろんなアカウントに権限付与できるものがあると良さそう。

**Comment by sevenc-nanashi** [comment]
GitHubのorg（teamかも？）に権限を付与できるっぽいです。
Orgをメインオーナーにすることはできなさそうなので、一人人柱になる必要はあるっぽそう？

**Comment by Hiroshiba** [comment]
なるほどです。ちょっと若干よくわからないですね･･･！どうやってアカウントの整合性取るんだろ。

Rust周りのことは @qryxip さんにお任せできると嬉しそうだからアカウントもお任せするのが良い･･･かもと思いましたが、他の人が実質認証トークンにアクセスできてしまうのは良くないですね･･･。
また僕のアカウントとかにすると良さそうかな。
というかVOICEVOX用のアカウントを作ると良かったり･･･？

**Comment by qryxip** [comment]
[crates.io: development update | Rust Blog](https://blog.rust-lang.org/2025/07/11/crates-io-development-update-2025-07/)

Trusted Publishingなる機能が入ったようです。crates.io側にリポジトリを登録することで、以下の形によるリリースが可能になるようです。

```yaml
    - uses: rust-lang/crates-io-auth-action@v1
      id: auth
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
```

これなら

> 認証トークン

のことは考えなくて良くなるかなと。
